image: golang:1.6

before_script:
    - mkdir -p $GOPATH/src/ci.guzzler.io/guzzler
    - cp -r ../../guzzler $GOPATH/src/ci.guzzler.io
    - cd $GOPATH/src/ci.guzzler.io/guzzler/corcel

stages:
    - build

job1:
    stage: build
    script:
        - make install
        - make build
        - make test
