image: golang:1.5.1

before_script:
    - cp -r ../../guzzler $GOPATH/src
    - cd $GOPATH/src/guzzler/corcel

stages:
    - build

job1:
    stage: build
    script:
        - go get -t
        - go build
        - go test -cover
