language: go
sudo: false

go:
   - 1.5

env:
   global:
      - BUILD_GOARCH=amd64
   matrix:
      - BUILD_GOOS=linux
      - BUILD_GOOS=darwin
      - BUILD_GOOS=windows

before_install:
   - go get github.com/mitchellh/gox
   - gox -build-toolchain
   - go get github.com/tcnksm/ghr
   - go get github.com/axw/gocov/gocov
   - go get github.com/mattn/goveralls
   - go get code.google.com/p/go.tools/cmd/cover

after_success:
   - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
   - ghr --username tcnksm-sample --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/

install:
   - go get -t -v ./...

script:
   - go build
   - go test -v ./...
