language: go
sudo: false

go:
   - 1.5

env:
   global:
      - BUILD_GOARCH=amd64

before_install:
   - go get github.com/mitchellh/gox
   - go get github.com/tcnksm/ghr

after_success:
   - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
   - if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && 
       [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
       ghr --username reaandrew --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/  
     fi

install:
   - go get -t -v ./...

script:
   - go build
   - go test -v ./...
