language: go
sudo: false

go:
   - 1.5

env:
   global:
      - BUILD_GOARCH=amd64

before_install:
   - go get github.com/mitchellh/gox
   - go get github.com/tcnksm/ghr

after_success:
   - bash ./ci/deploy-to-github.sh

install:
   - go get -t -v ./...

script:
   - go build
   - go test -v ./...
